name: hitpal
description: "Hitpal"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.5
  http: ^1.2.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0
  flutter_verification_code: ^1.1.7
  email_validator: ^2.1.16

  phone_form_field:
    path: phone_form_field
  gallery_picker: ^0.5.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  image_path: "assets/images/appicon.png"
  android: true
  ios: true
  macOs: true
  remove_alpha_ios: true
  android_12:
    image_path: "assets/images/appicon.png"
  macos:
    generate: true
    image_path: "assets/images/appicon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#624AE0"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Thunder
      fonts:
        - asset: assets/fonts/thunder/Thunder-BoldLC.ttf
        - asset: assets/fonts/thunder/Thunder-BoldHC.ttf
        - asset: assets/fonts/thunder/Thunder-HC.ttf
        - asset: assets/fonts/thunder/Thunder-LC.ttf
        - asset: assets/fonts/thunder/Thunder-BlackHC.ttf
        - asset: assets/fonts/thunder/Thunder-MediumHC.ttf
        - asset: assets/fonts/thunder/Thunder-SemiBoldLC.ttf
        - asset: assets/fonts/sf/SF-Pro-Display-Black.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Heavy.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Light.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Semibold.otf